# Generated by Django 2.2.9 on 2021-05-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('TEMPERATURE', 'Temperatura'), ('HUMIDITY', 'Humedad')], max_length=100)),
                ('manufacturer_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
