# Generated by Django 3.2.10 on 2023-03-18 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='max_threshold',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='min_threshold',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='was_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SensorUserAlarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_email', models.BooleanField()),
                ('is_sms', models.BooleanField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sensors.sensor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='alarms',
            field=models.ManyToManyField(through='app_sensors.SensorUserAlarm', to=settings.AUTH_USER_MODEL),
        ),
    ]
