# Generated by Django 3.2.10 on 2023-03-18 17:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_sensors', '0003_alter_sensor_site'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sensoruseralarm',
            unique_together={('user', 'sensor')},
        ),
    ]
