# Generated by Django 3.2.10 on 2023-03-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sensors', '0004_alter_sensoruseralarm_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='manufacturer_id',
            new_name='unique_id',
        ),
    ]
