# Generated by Django 3.2.10 on 2023-05-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sensors', '0005_rename_manufacturer_id_sensor_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
