# Generated by Django 3.2.10 on 2023-05-20 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sensors', '0006_sensor_device_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='device_type',
            new_name='sensor_type',
        ),
    ]
