# Generated by Django 3.2.10 on 2023-09-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sensors', '0007_rename_device_type_sensor_sensor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='last_energy_state',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='last_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='last_value_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
