# Generated by Django 3.2.10 on 2023-12-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sensors', '0008_auto_20230920_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='last_value_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='last_value_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
