# Generated by Django 3.2.10 on 2023-12-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sensors', '0009_auto_20231228_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='last_value_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='last_value_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
