# Generated by Django 3.2.10 on 2023-12-28 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sensors', '0010_auto_20231228_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='last_value_date_time',
        ),
    ]
