# Generated by Django 3.2.10 on 2023-12-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sensors', '0011_remove_sensor_last_value_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='last_broker',
            field=models.CharField(choices=[('java', 'Java Server'), ('emqx', 'EMQX')], default='emqx', max_length=100),
            preserve_default=False,
        ),
    ]
