# Generated by Django 4.2.13 on 2025-01-18 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sensors', '0014_device_alter_sensor_sensor_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='device_id',
        ),
        migrations.AddField(
            model_name='sensor',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data', to='app_sensors.device'),
        ),
    ]
