# Generated by Django 4.2.13 on 2025-01-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sensors', '0017_sensor_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='is_unknow',
            field=models.BooleanField(default=False),
        ),
    ]
