# Generated by Django 3.2.10 on 2023-05-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0002_data_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='date',
        ),
        migrations.RemoveField(
            model_name='data',
            name='time',
        ),
        migrations.AlterField(
            model_name='data',
            name='datetime',
            field=models.DateTimeField(default='2023-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
