# Generated by Django 3.2.10 on 2023-05-19 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0003_auto_20230519_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='datetime',
            new_name='date_time',
        ),
    ]
