# Generated by Django 3.2.10 on 2023-12-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0004_rename_datetime_data_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
