# Generated by Django 3.2.10 on 2023-12-28 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0005_auto_20231228_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
