# Generated by Django 3.2.10 on 2023-12-28 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_data', '0006_alter_data_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='date_time',
        ),
    ]
