# Generated by Django 3.2.10 on 2023-03-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organizations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='city',
            field=models.CharField(default='cali', max_length=100),
            preserve_default=False,
        ),
    ]
