# Generated by Django 3.2.10 on 2023-09-20 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_organizations', '0004_auto_20230318_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='app_organizations.organization'),
        ),
    ]
