# Generated by Django 4.2.13 on 2024-06-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_organizations', '0005_alter_site_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='empresa_id_amarey',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
